### ISSUE TITLE
Unitree_go1

### ISSUE THREAD

**Issue by Muteeb125** [snt-arg/unitree_ros#29]
I cannot clearly understand what is the purpose of this package. What will be the output. Can you show a demo video by using that package.

**Comment by PedroS235** [comment]
Hello @Muteeb125,
This package allows you to control unitree go1 with ros2, meaning you can send velocity commands to the robot. In addition, you can receive the odometry and IMU.

This allows you for instance to have navigation2 stack command your robot. Of course, you will need extra sensors in this case, like a lidar.

Hope this answers your question.

**Comment by Muteeb125** [comment]
Can you show me any demo video how can I receive the odemtery and IMU

**Comment by PedroS235** [comment]
I do not have the time for the moment to record a video.

In case you are using Wi-Fi, make sure you connect to the unitree wifi hotspot. Then launch `ros2 launch unitree_ros unitree_driver_launch.py wifi:=true`. This will initialize the driver. If it can find the robot ip, it will publish the odometry to `/odom` and the imu to `/imu`. In case you want to move the robot, you need to publish to `/cmd_vel`. For standing up/down the robot, you need to send an empty message to the topic `/stand_up` and `/stand_down` respectively

**Comment by Muteeb125** [comment]
Thanks for clarification. My goal is to move my robot through GPS waypoints. I have already build an package of SDK and move robot to any position. Now I wants to recieve odm from IMU and move my robot accroding to the waypoints.

**Comment by PedroS235** [comment]
That is totally possible. But of course that you need to have other programs that interpret the way-points and sends the appropriate commands to the robot. There is a possibility to send a position instead of the velocity command. However, that is not implemented on the ros side of this driver yet.

**Comment by Muteeb125** [comment]
Thank you so much for your guidence. Is it possible can I get your email for better communication in future.

**Comment by PedroS235** [comment]
Yes sure! pmbs.123@gmail.com

**Comment by Muteeb125** [comment]
I just run the code but it is not showing any odm?
![Driver](https://github.com/user-attachments/assets/d84128c3-adb5-47a4-817f-1f51beca91da)

**Comment by PedroS235** [comment]
you need to open a new terminal and do `ros2 topic echo /odom`

**Comment by Muteeb125** [comment]
Than you so much it is working now. Can you please specify how to move the robot by giving the cmd velocity, I am giving the value but it is not moving
![Screenshot from 2024-07-19 02-29-32](https://github.com/user-attachments/assets/750bb4d7-7be7-4b2c-a579-b25caabf3379)

**Comment by PedroS235** [comment]
first be sure to not use any other driver other than this one, as others could be overwriting. Use teleop_keyboard tool to move the robot: `ros2 run teleop_twist_keyboard teleop_twist_keyboard`.

**Comment by PedroS235** [comment]
Closing this issue!
